### ISSUE TITLE
Memory Leak from loaded_modules->filename

### ISSUE THREAD

**Issue by cipherboy** [latchset/libverto#1]
(In relation to this [trace](https://pagure.io/gssproxy/issue/176#comment-450967))

I've been trying to track down why `filename` is leaking from [here](https://github.com/npmccallum/libverto/blob/master/src/verto.c#L260). As far as I can see, `loaded_modules` itself is also never freed. In particular, gssproxy calls `verto_default(...)` with `impl==NULL` [here](https://pagure.io/gssproxy/blob/master/f/proxy/src/gp_init.c#_110). The resulting `vctx` is later free-d in a bunch of places, including [here](https://pagure.io/gssproxy/blob/master/f/proxy/src/gssproxy.c#_285). However, it appears that `loaded_modules` is not touched as part of that [call](https://github.com/npmccallum/libverto/blob/master/src/verto.c#L550). 

As far as I understand it, this could be desired behavior in case an application wants to open a second event loop (e.g., the [test cases](https://github.com/npmccallum/libverto/blob/master/tests/test.h#L73_L89)); thus it would appear an explicit `verto_cleanup()` call would be needed to free `filename`/`loaded_modules`.

Should this be added to `verto_free(...)`, or a new `verto_cleanup()` call?

cc: @simo5 @frozencemetery

**Comment by frozencemetery** [comment]
(It would be pretty trivial to call such a function in krb5 and gssproxy
where needed.)

**Comment by frozencemetery** [comment]
Fixed in 4f58419fefadbc5c59c6d69b5aa2e1abf5c830c7
