### ISSUE TITLE
verto_new fails when libverto is built as a static library

### ISSUE THREAD

**Issue by madebr** [latchset/libverto#28]
When building libverto as a static library,
then `verto_new` returns `NULL`.

Building it as a shared library works though.

**Comment by frozencemetery** [comment]
Hi, when building as a static library, you'll need to include a backend to be the builtin default.  It sounds like this step was not performed, so verto couldn't find any backends, and thus `verto_new()` returned `NULL`.

**Comment by madebr** [comment]
Thanks for the answer!
That was indeed the case.
Is calling `verto_cleanup()` allowed when using a built-in event library?
The test below fails with a segmentation error when using a builtin libev, libevent or glib.
When using `tevent` as backend, `verto_new` keeps failing.

The test *works* when using a non-builtin event backend.
But I'm not a libverto expert.

```c
#include "verto.h"

#include <stdio.h>
#include <stdlib.h>

struct timeout_info {
    int count;
};

static void on_timeout(verto_ctx *ctx, verto_ev *ev) {
    struct timeout_info *tinfo = (struct timeout_info *) verto_get_private(ev);
    tinfo->count++;
    printf("callback called: %d\n", tinfo->count);
    fflush(stdout);
    if (tinfo->count != 20) {
        verto_set_private(ev, NULL, NULL);
        verto_ev *ev_new = verto_add_timeout(ctx, VERTO_EV_FLAG_NONE, on_timeout, 50);
        verto_set_private(ev_new, tinfo, NULL);
    } else {
        verto_break(ctx);
    }
}

int main(int argc, char *argv[])
{
    verto_ctx *ctx;
    verto_ev *ev;

    if (argc < 2) {
        fprintf(stderr, "Need an argument\n");
        return 1;
    }

    ctx = verto_new(argv[1], VERTO_EV_TYPE_TIMEOUT);
    if (ctx == NULL) {
        fprintf(stderr, "verto_new failed\n");
        return 1;
    }
    struct timeout_info *tinfo = (struct timeout_info*) malloc(sizeof(struct timeout_info));
    tinfo->count = 0;
    ev = verto_add_timeout(ctx, VERTO_EV_FLAG_NONE, on_timeout, 50);
    verto_set_private(ev, tinfo, NULL);
    if (ev == NULL) {
        fprintf(stderr, "verto_add_timeout failed\n");
        return 1;
    }

    verto_run(ctx);
    free(tinfo);

    verto_free(ctx);
    verto_cleanup();  // <= munmap_chunk(): invalid pointer here
    return 0;
}
```

**Comment by madebr** [comment]
I notice that tevent is handled differently in the configure script.
See https://github.com/latchset/libverto/blob/main/configure.ac#L72-L90
When adding:
```sh
            default) WITH_TEVENT=default;;
            builtin) WITH_TEVENT=builtin;;
```
then tevent used as a builtin backend also fails on `verto_cleanup`.

**Comment by frozencemetery** [comment]
`verto_cleanup` is not something that should be done with a static library.  The rationale is outlined in the [verto.h file](https://github.com/latchset/libverto/blob/main/src/verto.h#L85-L88).  That is, if you're static, you can pick a backend at compile time just fine.  And if you want to dynamically switch backends, you shouldn't be static, you should be dynamic :)

tevent is handled differently because it doesn't really behave itself - see https://github.com/latchset/libverto/issues/16 .  But you don't need to patch configure.ac to expose it; you can just pass --with-tevent=yes if you actually want that...

**Comment by madebr** [comment]
Thanks for the explanation.

I asked about talloc because I was creating a conan recipe for verto.

**Comment by frozencemetery** [comment]
Sure thing.  Not that you asked for my opinion, but I recommend not providing support for it in packages - I don't in Fedora/RHEL/CentOS, and the Debian/Ubuntu maintainer doesn't either.  (Haven't checked what other distros do.)

**Comment by madebr** [comment]
Thanks for your opinion.
I'll emit a warning saying tevent is not recommended by the developers of libverto.
